---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: {{ .Values.service.protocol }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
subsets:
  - addresses:
      - ip: {{ .Values.hostIP }}
    ports:
      - port: {{ .Values.port }}
