apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mysql.name" . }}
  labels:
    app: {{ template "mysql.name" . }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mysql.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mysql.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.image.repository }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - name: {{ template "mysql.name" . }}
          containerPort: {{ .Values.internalPort }}
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.pvc.name }}
          mountPath: "/var/lib/mysql"
      volumes:
      - name: {{ .Values.pvc.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}