---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.name" . }}-client
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "mysql.name" . }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}