apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  RABBIT_USER: {{ .Values.rabbitmq.user }}
  RABBIT_PORT: {{ .Values.rabbitmq.port | quote }}
  RABBIT_SERVER: {{ .Values.rabbitmq.server }}
  RABBIT_VHOST: {{ .Values.rabbitmq.vhost | quote }}
  DB_SERVER: {{ .Values.mysql.server }}