apiVersion: v1
description: Filebeat for elastic stack.
home: https://github.com/elastic/helm-charts
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: logging-filebeat
version: 7.5.2
appVersion: 7.5.2
sources:
  - https://github.com/elastic/beats
icon: https://helm.elastic.co/icons/beats.png
