---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-files
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.files }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
binaryData:
 {{- range $key, $value := .Values.binaryFiles }}
   {{ $key }}: |-
{{ $value | indent 4   }}
 {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-patterns
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.patterns }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-pipeline
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.inputs }}
  input_{{ $key }}.conf: |-
{{ $value | indent 4 }}
{{- end }}

{{- range $key, $value := .Values.filters }}
  filter_{{ $key }}.conf: |-
{{ $value | indent 4 }}
{{- end }}

{{- range $key, $value := .Values.outputs }}
  output_{{ $key }}.conf: |-
{{ $value | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-elasticsearch-templates
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- $files := .Files }}
{{- range $path, $bytes := .Files.Glob "elasticsearch-templates/*" }}
  {{ $path | replace "/" "-" }}: |-
{{ $files.Get $path | indent 4 }}
{{- end }}